### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by khalilo80** [Odoo-mobile/framework#101]
![error](https://cloud.githubusercontent.com/assets/15094754/11068263/cddea2c6-87d0-11e5-8c1e-cdbb6261bc2f.png)

I got this error ?

**Comment by Kelbethor** [comment]
I've done a pull request. 
You can check:
https://github.com/Kelbethor/framework/commit/51441f1ac05c5d2f46b7f5a91a5b6e72a8483741

**Comment by khalilo80** [comment]
Thanks alot, but when i run the application on my samsung tab 10.1, the app is stopped and showing this message"Unfortunatly, odoo as stopped"

**Comment by Kelbethor** [comment]
Did app compile? (I asume so because you're running it at device) If it works: What is the new issue? 

Enviado desde Yahoo Mail con Android 
 
  El sáb 14 14e nov 14e 2015 a las 12:15, khalilo80<notifications@github.com> escribió:   
Thanks alot, but when i run the application on my samsung tab 10.1, the app is stopped and showing this message"Unfortunatly, odoo as stopped"

**Comment by khalilo80** [comment]
i connect my samsung tab with my pc to run the android app on it, when i run the app from android studio and choose samsung device to run, it run perfectly but once i put the login info like username password and add self host iand press login it stopped??!!

**Comment by Kelbethor** [comment]
Well, as I asumed app compiled, but there is other runtime error. Do you hace any clues to help me to help? Logcat? Any stacktrace?

Enviado desde Yahoo Mail con Android 
 
  El sáb 14 14e nov 14e 2015 a las 12:31, khalilo80<notifications@github.com> escribió:   
i connect my samsung tab with my pc to run the android app on it, when i run the app from android studio and choose samsung device to run, it run perfectly but once i put the login info like username password and add self host iand press login it stopped??!!

**Comment by khalilo80** [comment]
![11](https://cloud.githubusercontent.com/assets/15094754/11163362/7b050cb2-8acc-11e5-9fe5-a76f16d8328c.png)

**Comment by Kelbethor** [comment]
Weeeelll.... We're entering uncomfrotable issue for me as a newbie android developer. For me, it seems build settings issue (Android build and/or target sdk version or maybe of your device android version) . You should post build configuration and mybe others could guide you. (I can't because I can't say same sdk is used and I don't have experience across multiple sdk (I'm curretly working on 22 targeting 19 device) )

**Comment by dpr-odoo** [comment]
@khalilo80 

May be you have already installed app from PlayStore build with Odoo Mobile framework. When compile with your android studio it generate debug application. It saying that your (debug application) and play store app (released app) caller uid is different. 

Because, framework share same user account it required that each of the app works on same caller uid.

For testing your application, you need to remove all other app installed from Play Store. 

May this will help you.

**Comment by khalilo80** [comment]
The problem has been solved for me. Let me explain what happened.
When the application through Samsung tab 10.1 which is connected to my laptop the login page is worked and when i submitted my credentials the error is shown. but when I am using geneymotion emulator, everything is worked correctly.
