### ISSUE TITLE
How to first sync AService.java,after AService.java finish then sync BService.java?

### ISSUE THREAD

**Issue by mikedream89** [Odoo-mobile/framework#197]
hi,guys:
How to first sync `AService.java` ,after `AService.java` finish then sync `BService.java`?

**Comment by kasim1011** [comment]
@mikedream89 

have a look at my sample [Odoo-mobile-quick-start](https://github.com/kasim1011/Odoo-mobile-quick-start). Look, it is deprecated. since `framework v2.2.0` has release so, don't create your entire app on that. Just look at [SyncFragment.java](https://github.com/kasim1011/Odoo-mobile-quick-start/blob/master/app/src/main/java/com/odoo/addons/partners/SyncFragment.java). It might help you.

**Comment by mikedream89** [comment]
@kasim1011 
It(Odoo-mobile-quick-start) could not sync data from server. 
Why?

**Comment by mikedream89** [comment]
thanks @kasim1011   i fix it.

**Comment by kasim1011** [comment]
It's my pleasure @mikedream89 
can you please tell me what was the issue?

**Comment by mikedream89** [comment]
it is not issue, it's only my a question. ：－Ｄ
