### ISSUE TITLE
DiskBasedCache.streamToBytes : OutOfMemoryError

### ISSUE THREAD

**Issue by r-mckay** [Odoo-mobile/framework#216]
Hello!

We encounter the crash below during our synchronizations with the server.
Unfortunately, it seems that the involved part is not reachable in the code framework. We do not find the code that could handle this.
Is there any way to solve or prevent this crash from happening?

Thank you in advance!

Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 1869562681 byte allocation with 16777216 free bytes and 495MB until OOM
com.android.volley.toolbox.DiskBasedCache.streamToBytes (DiskBasedCache.java:322)
com.android.volley.toolbox.DiskBasedCache.readString (DiskBasedCache.java:540)
com.android.volley.toolbox.DiskBasedCache.readStringStringMap (DiskBasedCache.java:563)
com.android.volley.toolbox.DiskBasedCache$CacheHeader.readHeader (DiskBasedCache.java:403)
com.android.volley.toolbox.DiskBasedCache.initialize (DiskBasedCache.java:156)
com.android.volley.CacheDispatcher.run (CacheDispatcher.java:84)

**Comment by r-mckay** [comment]
Probably in relation with the RPC aar (#222).
What do you think @dpr-odoo @asa-odoo ?
Thanks!

**Comment by dpr-odoo** [comment]
@r-mckay this issue is related to your memory when you are trying to get large data and os not able to cache it all. Internally aar uses [Volley](https://developer.android.com/training/volley/index.html), try with limiting data requests (records limit) in your service will solve this.

Set ``syncDataLimit()`` [See example](http://mobile.odoo.co.in/v2/getting-started/working-with-odoo-mobile/components/base-classes.html#performdatasync)

**Comment by r-mckay** [comment]
@dpr-odoo Thank you for your answer.
I agree that it may solve this issue but this is not what I need. Indeed, I would like to synchronize all the data and not a subset of it. I see that there is an offset in the request. Is it possible to play with it and perform a sync by pagination?
Furthermore, concerning this internal aar, could you please take a look at #222 ?
Thank you for your time.
