### ISSUE TITLE
Table synchronization issue

### ISSUE THREAD

**Issue by amar-teckzilla** [Odoo-mobile/framework#284]
I want add domain filter
I have code some what like these
In class A {
@Odoo.hasDomainFilter()
    OColumn product_opd = new OColumn("Product OPd",Product_Product.class,OColumn.RelationType.ManyToOne).setHasDomainFilterColumn(true).addDomain("categ_product_id","=",2);
}

In class B{
 OColumn name = new OColumn("Name", OVarchar.class).setRequired();
    OColumn categ_product_id = new OColumn("Catgeory",ProductCategory.class, OColumn.RelationType.ManyToOne);
}

over here i am able to get the name from class B but not able to fetch categ_product_id and not able to fetch ProductCategory Table.
Any Suggestion regards these problem would be helpful.
Thank You.

**Comment by dpr-odoo** [comment]
@amar-teckzilla 
``@Odoo.hasDomainFilter`` removed in recent commits because its not working perfectly as well has bug. 

The new way to applying domain at runtime with ``@Odoo.Domain()`` annotation merged.
You can check doc : http://odoo-mobile-doc-v2.readthedocs.io/en/latest/getting-started/working-with-odoo-mobile/components/base-classes.html#odoo-domain

For more detail please check issue comment : https://github.com/Odoo-mobile/framework/issues/268#issuecomment-264770815
