### ISSUE TITLE
One2Many Issue

### ISSUE THREAD

**Issue by maanu** [Odoo-mobile/framework#68]
How to get One2Many field using CursorLoader?

**Comment by salahzidi** [comment]
You can get it by using the "ODataRow" function: yourDataRow.getO2MRecord(yourOneToManyItemId)

**Comment by maanu** [comment]
I know that function.but it fails to work in case of using cursor Loader as you might know that it uses pure SQLITE database for fetching record.so it doesn't store value in table that has ONE side key..we can only use M2O relationship.It causes null pointer exception when I'm trying to fetch record as you suggest.

**Comment by dpr-odoo** [comment]
Hello,

It is not possible to directly access one to many record using CursorLoader.

CursorLoader create cursor record set which are related to your table column. It not automatically handle relations such as One2Many or Many2Many. 

For accessing one 2 many record when you are binding your view with record cursor you have to just fetch ODataRow using your database object by db.select(your cursor's _id row value as int) and than you can get your one 2 many record by datarow.getO2MRecord("column").browseEach().

E.g:

ODataRow row = db.select(cr.getInt(cr.getColumnIndex("_id"));

**Comment by maanu** [comment]
Thank you so much for your reply.:)
Can you please help me to understand the whole process of this framework.
I mean to say how services running and when it calls??..Its same process as
the older one framework..?
I am getting some difficulties to understand work of services and syncing
data in new framework.can you please explain me briefly.??
It would be easier for me to understand if you help me.;)
Thanks in advance:

On Thu, Apr 9, 2015 at 10:48 AM, Dharmang Soni <notifications@github.com>
wrote:

> Hello,
>
> It is not possible to directly access one to many record using
> CursorLoader.
>
> CursorLoader create cursor record set which are related to your table
> column. It not automatically handle relations such as One2Many or
> Many2Many.
>
> For accessing one 2 many record when you are binding your view with record
> cursor you have to just fetch ODataRow using your database object by
> db.select(your cursor's _id row value as int) and than you can get your one
> 2 many record by datarow.getO2MRecord("column").browseEach().
>
> E.g:
>
> ODataRow row = db.select(cr.getInt(cr.getColumnIndex("_id"));
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Odoo-mobile/framework/issues/68#issuecomment-91118060>
> .
>



-- 

*NICE DAY...*

**Comment by SELKHOUFAIRI** [comment]
Hi,
please tell me if odoo mobile framwork manage access rights based on groups? 
Regards

**Comment by dpr-odoo** [comment]
@maanu Refer Odoo Mobile documentation (v2) http://mobile.odoo.co.in/v2

**Comment by dpr-odoo** [comment]
@SELKHOUFAIRI  Odoo Mobile framework uses JSON-RPC for getting and submitting data on server. Odoo Server check access rights based on RPC calls. So on mobile, we don't need to check for access rights of user, it already checked by server on your request for data.

**Comment by SalouaELKHOUFAIRI** [comment]
Thank you @Dharmang :)

----------------------------------------------------------------------------------
Saloua ELKHOUFAIRI
Elève Ingénieur en Réseaux Informatiques et Systèmes d'Information
Faculté des Sciences et Techniques -Gueliz-Marrakech

2015-05-28 6:54 GMT+01:00 Dharmang Soni <notifications@github.com>:

**Comment by dpr-odoo** [comment]
@SalouaELKHOUFAIRI Its @dpr-odoo :wink:

**Comment by fabermandeke** [comment]
Hi, currently I am working on a mobile app with Odoo mobile framework which is supposed to use some features of the survey module (answer questions from the mobile app), at first I just try to fetch the questions.
Models are structured in this way:
Survey.survey has a relationship o2many with survey.page, and survey.page has another o2many relation with survey .question,  I retrieve the pages well into the activity surveyDetail  like this:
…
survey = new SurveySurvey(this, null);
…
int rowId = extras.getInt(OColumn.ROW_ID);
record = survey.browse(rowId);
…
List<ODataRow> lines = record.getO2MRecord("page_ids").browseEach();

The problem is that I do not get the questions in PageDetail with this:
…
record = page.browse(rowId);
…
List<ODataRow> lines = record.getO2MRecord("question_ids").browseEach();

I get null but there are questions in server.
And Whereas this:  record.getO2MRecord("question_ids")    I have this in log: odoo.core.orm.OO2Mrecord@41896e98
can I have your support?
